// src/constants/index.js
export const LISTA_UTDS = [
  "ALAGOINHAS", "ESPLANADA", "PAULO AFONSO", "RIBEIRA DO POMBAL", "JACOBINA",
  "JUAZEIRO", "REMANSO", "SENHOR DO BONFIM", "CONCEICAO DO COITE", "FEIRA DE SANTANA NORTE",
  "FEIRA DE SANTANA SUL", "SANTO AMARO", "SERRINHA", "CAMACARI", "CANDEIAS",
  "LAURO DE FREITAS", "GRACA", "ITAPOAN", "PERIPERI", "PIRAJA", "PITUBA",
  "AMARGOSA", "IPIAU", "SANTO ANTONIO DE JESUS", "VALENCA", "EUNAPOLIS",
  "ILHEUS", "ITABUNA", "PORTO SEGURO", "POSTO DA MATA", "TEIXEIRA DE FREITAS",
  "BRUMADO", "GUANAMBI", "ITAPETINGA", "VITORIA DA CONQUISTA", "IRECE",
  "ITABERABA", "JEQUIE", "LIVRAMENTO DE NOSSA SENHORA", "SEABRA", "BARREIRAS",
  "BOM JESUS DA LAPA", "IBOTIRAMA", "LUIS EDUARDO MAGALHAES", "SANTA MARIA DA VITORIA"
];

export const POSTOS_OPERACIONAIS = [
  "Feira de Santana", "Serrinha", "Alagoinhas", "Jacobina", "Juazeiro"
];